In [1]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv('D:\\exe_file\\machine_learning\\stock_price_predictor\\google.csv')
df

           Date     Open     High     Low    Close    Volume
0     30-Jun-17   943.99   945.00  929.61   929.68   2287662
1     29-Jun-17   951.35   951.66  929.60   937.82   3206674
2     28-Jun-17   950.66   963.24  936.16   961.01   2745568
3     27-Jun-17   961.60   967.22  947.09   948.09   2443602
4     26-Jun-17   990.00   993.99  970.33   972.09   1517912
5     23-Jun-17   975.50   986.62  974.46   986.09   1563985
6     22-Jun-17   976.87   980.50  973.31   976.62   1009476
7     21-Jun-17   970.79   979.67  969.16   978.59   1161607
8     20-Jun-17   975.31   980.79  968.20   968.99   1297287
9     19-Jun-17   969.65   979.30  968.20   975.22   1468837
10    16-Jun-17   957.91   959.95  948.70   958.62   2559207
11    15-Jun-17   948.02   960.68  940.37   960.18   2427639
12    14-Jun-17   975.50   979.70  959.51   967.93   1505486
13    13-Jun-17   972.04   977.91  962.01   970.50   2005356
14    12-Jun-17   958.72   968.00  936.80   961.81   4202109
15     9-Jun-17  1005.49  1005.50  953.37   970.12   3647857
16     8-Jun-17  1004.23  1005.60  996.62  1004.28   1687925
17     7-Jun-17   998.82  1003.91  995.81  1001.59   1374097
18     6-Jun-17  1003.31  1008.61  994.80   996.68   1552114
19     5-Jun-17   997.89  1007.40  995.45  1003.88   1378916
20     2-Jun-17   988.59   996.48  987.07   996.12   1735469
21     1-Jun-17   990.96   993.14  981.29   988.29   1306384
22    31-May-17   996.21   999.60  981.68   987.09   1724095
23    30-May-17   992.50   997.62  991.36   996.17   1516685
24    26-May-17   992.00   996.39  987.36   993.27   1636416
25    25-May-17   979.00   995.78  977.82   991.86   1954149
26    24-May-17   975.26   978.12  971.63   977.61   1142488
27    23-May-17   969.96   974.51  964.50   970.55   1545421
28    22-May-17   957.00   964.82  956.56   964.07   1387392
29    19-May-17   952.82   959.56  952.00   954.65   1360299
...         ...      ...      ...     ...      ...       ...
3115  14-Feb-05    91.52    96.64   90.59    96.59  38576169
3116  11-Feb-05    93.42    96.26   93.13    93.79  13126137
3117  10-Feb-05    96.08    96.20   92.72    94.08  18986725
3118   9-Feb-05   100.48   100.90   94.82    95.89  17310425
3119   8-Feb-05    98.58   100.11   97.36    99.42  11493216
3120   7-Feb-05   102.73   103.30   97.85    98.11  12981698
3121   4-Feb-05   103.34   103.98  101.40   102.28  14823134
3122   3-Feb-05   103.10   106.79  103.01   105.54  13005885
3123   2-Feb-05   107.88   108.51  101.93   103.08  32874261
3124   1-Feb-05    97.29   101.98   95.41    96.05  19153969
3125  31-Jan-05    96.94    98.28   95.96    97.91   9600561
3126  28-Jan-05    95.11    97.45   93.26    95.27  12212727
3127  27-Jan-05    94.47    94.52   92.69    94.13   6631221
3128  26-Jan-05    89.72    94.80   89.66    94.71  12345935
3129  25-Jan-05    91.19    91.21   88.23    88.65  10696013
3130  24-Jan-05    94.44    94.76   90.25    90.45  14034232
3131  21-Jan-05    97.32    97.78   94.15    94.23   9294685
3132  20-Jan-05    96.39    98.22   96.10    97.06   9003777
3133  19-Jan-05   102.42   102.75   98.45    98.75  11351583
3134  18-Jan-05   100.55   102.61   99.43   102.05  13237127
3135  14-Jan-05    98.10   100.11   97.16   100.08   9643747
3136  13-Jan-05    97.79    98.79   97.12    97.76   6852573
3137  12-Jan-05    97.26    98.06   95.35    97.79   8361295
3138  11-Jan-05    97.91    98.95   96.69    96.87   6962544
3139  10-Jan-05    97.35    99.15   96.01    97.63   7554795
3140   7-Jan-05    95.42    97.22   94.48    97.02   9666175
3141   6-Jan-05    97.72    98.05   93.95    94.37  10389803
3142   5-Jan-05    96.82    98.55   96.21    96.85   8239545
3143   4-Jan-05   100.77   101.57   96.84    97.35  13762396
3144   3-Jan-05    98.80   101.92   97.83   101.46  15860692

[3145 rows x 6 columns]